### ISSUE TITLE
/shorten url issues

### ISSUE THREAD

**Issue by GglServe** [abhishekbalam/keeplinkin#3]
- GET request to /shorten without url parameter returns 500, better to return 400.
- Get request does not return correct url (missing slash / after site url). 
Expected response (example) - https://keeplink.in/ABC
Actual response - https://keeplink.inABC

**Comment by abhishekbalam** [comment]
Thanks for noticing this. Will fix it soon.

**Comment by abhishekbalam** [comment]
Made changes according to both your points.
Thanks alot for pointing them out.
